# use a temporary file for history
HISTFILE=<%= history_file %>

# don't truncate the history file on exit
HISTFILESIZE=-1

# keep a very long history in memory, that will
# be copied to HISTFILE on exit
# Negative values (do not limit) will not work
# in some Bash versions
HISTSIZE=10000

# don't keep timestamps in history
unset HISTTIMEFORMAT

# don't skip any command
HISTCONTROL=""

# change prompt
PS1="\e[1;33mdry-running\e[m:\w\$ "

# add default commandline switches
alias ant='<%= ant_commandline %>'
alias mvn='<%= mvn_commandline %>'