# use a temporary file for history
HISTFILE=<%= history_file %>

# don't truncate the history file on exit
HISTFILESIZE=-1

# keep a very long history in memory, that will
# be copied to HISTFILE on exit.
# Note: 100000 is usually safe enough for a build session.
HISTSIZE=100000

# don't keep timestamps in history
unset HISTTIMEFORMAT

# don't skip any command (record duplicates and spaces)
HISTCONTROL=""

# change prompt to indicate dry-run mode
# Check if tput exists to avoid errors in minimal environments
if command -v tput >/dev/null 2>&1; then
  PS1="\[$(tput bold)\]\[\033[38;5;11m\]dry-running\[$(tput sgr0)\]\[\033[38;5;15m\]:\w\\$ \[$(tput sgr0)\]"
else
  PS1="dry-running:\w\$ "
fi

# add default commandline switches

<% unless ant_in_kit %>
echo -e "\033[0;31mWARNING: ant executable file not found in kit/, please check that it is present and executable."
echo -e "Defaulting to system-provided ant, this could make your builds non-reproducible.\033[0m"
<% end %>
alias ant='<%= ant_commandline %>'

<% unless mvn_in_kit %>
echo -e "\033[0;31mWARNING: mvn executable file not found in kit/, please check that it is present and executable."
echo -e "Defaulting to system-provided mvn, this could make your builds non-reproducible.\033[0m"
<% end %>
alias mvn='<%= mvn_commandline %>'

# Gradle wrapper alias
alias gradlew='<%= gradle_commandline %>'