# use a temporary file for history
HISTFILE=<%= history_file %>

# don't truncate the history file on exit
HISTFILESIZE=-1

# keep a very long history in memory, that will
# be copied to HISTFILE on exit
# Negative values (do not limit) will not work
# in some Bash versions
HISTSIZE=10000

# don't keep timestamps in history
unset HISTTIMEFORMAT

# don't skip any command
HISTCONTROL=""

# change prompt
PS1="\[$(tput bold)\]\[\033[38;5;11m\]dry-running\[$(tput sgr0)\]\[$(tput sgr0)\]\[\033[38;5;15m\]:\w\\$ \[$(tput sgr0)\]"

# add default commandline switches

<% if !ant_in_kit %>
echo -e "\e[91mWARNING: ant executable file not found in kit/, please check that it is present and executable."
echo -e "\e[91mDefaulting to system-provided ant, this could make your builds non-reproducible."
<% end %>
alias ant='<%= ant_commandline %>'

<% if !mvn_in_kit %>
echo -e "\e[91mWARNING: mvn executable file not found in kit/, please check that it is present and executable."
echo -e "\e[91mDefaulting to system-provided mvn, this could make your builds non-reproducible."
<% end %>
alias mvn='<%= mvn_commandline %>'

alias gradlew='<%= gradle_commandline %>'
