inherit_from: .rubocop_todo.yml

require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: disable
  TargetRubyVersion: 3.1
  Exclude:
    - 'lib/template/*.spec'

Layout/LineLength:
  Max: 140

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 40

Metrics/AbcSize:
  Max: 50

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 20

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/MultilineBlockChain:
  Enabled: false
