inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.1
  NewCops: disable

Layout/LineLength:
  Max: 140

Metrics/BlockLength:
  Max: 200

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 40

Metrics/AbcSize:
  Max: 50

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 20

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/MultilineBlockChain:
  Enabled: false
