name: 'GitHub Action review'

on:
  push:
    branches: [ master, devel ]
    paths:
      - '.github/workflows/**'
  pull_request:
    branches: [ master, devel ]
jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      - uses: reviewdog/action-actionlint@d63ba7532e0942965320cd8d73cbae4c7b3c5283  # v1.65.2
