name: 'GitHub Action review'

on:
  push:
    branches: [ master, devel ]
    paths:
      - '.github/workflows/**'
  pull_request:
    branches: [ master, devel ]
jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@09d2acae674a48949e3602304ab46fd20ae0c42f  # v4.2.2
      - uses: reviewdog/action-actionlint@664c8ef5435569dd2880e62d891ab3ecdf98dc60  # v1.65.2
