name: Markdown

on:
  push:
    branches: [ master, devel ]
    paths:
      - '*.md'
      - '.github/workflows/markdown.yml'
      - '.markdownlint.yaml'
  pull_request:
    branches: [ master, devel ]
    paths:
      - '*.md'
      - '.github/workflows/markdown.yml'
      - '.markdownlint.yaml'

jobs:
  markdown:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # # v6.0.2
    - uses: DavidAnson/markdownlint-cli2-action@ded1f9488f68a970bc66ea5619e13e9b52e601cd  # main branch as there's no release with the fix yet

