name: Markdown

on:
  push:
    branches: [ master, devel ]
    paths:
      - '*.md'
      - '.github/workflows/markdown.yml'
      - '.markdownlint.yaml'
  pull_request:
    branches: [ master, devel ]
    paths:
      - '*.md'
      - '.github/workflows/markdown.yml'
      - '.markdownlint.yaml'

jobs:
  markdown:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@09d2acae674a48949e3602304ab46fd20ae0c42f  # v4.2.2
    - uses: DavidAnson/markdownlint-cli2-action@addcfda67fbf29409314acdbe47c6d219262fb44  # main branch as there's no release with the fix yet

