name: RuboCop

on:
  push:
    branches: [ devel ]
    paths:
      - '*.gemspec'
      - 'Gemfile'
      - 'Gemfile.lock'
      - 'bin/tetra'
      - 'lib/**.rb'
      - 'spec/**.rb'
      - '**.rb'
      - '.github/workflows/rubocop.yml'
      - '.rubocop_todo.yml'
      - '.rubocop.yml'
  pull_request:
    branches: [ master, devel ]
    paths:
      - '*.gemspec'
      - 'Gemfile'
      - 'Gemfile.lock'
      - 'bin/tetra'
      - 'lib/**.rb'
      - 'spec/**.rb'
      - '**.rb'
      - '.github/workflows/rubocop.yml'
      - '.rubocop_todo.yml'
      - '.rubocop.yml'

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
    - uses: ruby/setup-ruby@afeafc3d1ab54a631816aba4c914a0081c12ff2f  # v1.310.0
      with:
        ruby-version: '3.4'
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Install RuboCop via bundle
      run: bundle install
    - name: Run RuboCop
      run: |
        ruby --version
        bundle exec rubocop --version
        bundle exec rubocop 'bin/tetra'
        bundle exec rubocop 'lib/tetra.rb'
        bundle exec rubocop 'lib/tetra/'
        bundle exec rubocop 'spec/spec_helper.rb'
        bundle exec rubocop 'spec/lib'
        bundle exec rubocop 'tetra.gemspec'
