name: RuboCop

on:
  push:
    branches: [ devel ]
    paths:
      - '*.gemspec'
      - 'Gemfile'
      - 'Gemfile.lock'
      - 'bin/tetra'
      - 'lib/**.rb'
      - 'spec/**.rb'
      - '**.rb'
      - '.github/workflows/rubocop.yml'
      - '.rubocop_todo.yml'
      - '.rubocop.yml'
  pull_request:
    branches: [ master, devel ]
    paths:
      - '*.gemspec'
      - 'Gemfile'
      - 'Gemfile.lock'
      - 'bin/tetra'
      - 'lib/**.rb'
      - 'spec/**.rb'
      - '**.rb'
      - '.github/workflows/rubocop.yml'
      - '.rubocop_todo.yml'
      - '.rubocop.yml'

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
    - uses: ruby/setup-ruby@14594264cd68ce8a2345dd349bc3d138a4ef85c8  # v1.327.0
      with:
        ruby-version: '3.4'
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run RuboCop
      run: |
        ruby --version
        bundle exec rubocop --version
        bundle exec rubocop 'bin/tetra'
        bundle exec rubocop 'lib/tetra.rb'
        bundle exec rubocop 'lib/tetra/'
        bundle exec rubocop 'spec/spec_helper.rb'
        bundle exec rubocop 'spec/lib'
        bundle exec rubocop 'tetra.gemspec'
