name: RuboCop

on:
  push:
    branches: [ devel ]
    paths:
      - '*.gemspec'
      - 'Gemfile'
      - 'Gemfile.lock'
      - 'bin/tetra'
      - 'lib/**.rb'
      - 'spec/**.rb'
      - '**.rb'
      - '.github/workflows/rubocop.yml'
      - '.rubocop_todo.yml'
      - '.rubocop.yml'
  pull_request:
    branches: [ master, devel ]
    paths:
      - '*.gemspec'
      - 'Gemfile'
      - 'Gemfile.lock'
      - 'bin/tetra'
      - 'lib/**.rb'
      - 'spec/**.rb'
      - '**.rb'
      - '.github/workflows/rubocop.yml'
      - '.rubocop_todo.yml'
      - '.rubocop.yml'

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
    - uses: ruby/setup-ruby@6aaa311d81eba98ae12eaffbcb63296ace0efcde  # v1.307.0
      with:
        ruby-version: '3.4'
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Install RuboCop via bundle
      run: bundle install
    - name: Run RuboCop
      run: |
        ruby --version
        bundle exec rubocop --version
        bundle exec rubocop 'bin/tetra'
        bundle exec rubocop 'lib/tetra.rb'
        bundle exec rubocop 'lib/tetra/'
        bundle exec rubocop 'spec/spec_helper.rb'
        bundle exec rubocop 'spec/lib'
        bundle exec rubocop 'tetra.gemspec'
