name: Coarse tests

on:
  push:
    branches: [ master, devel ]
    paths:
      - '!*.md'
      - '*.gemspec'
      - '**.rb'
      - 'Rakefile'
      - 'Gemfile'
      - 'Gemfile.lock'
      - 'bin/tetra'
      - 'spec/**'
      - 'lib/template/bundled/'
      - '.github/workflows/test_coarse.yml'
  pull_request:
    branches: [ master, devel ]
    paths:
      - '!*.md'
      - '*.gemspec'
      - '**.rb'
      - 'Rakefile'
      - 'Gemfile'
      - 'Gemfile.lock'
      - 'bin/tetra'
      - 'spec/**'
      - 'lib/template/bundled/'
      - '.github/workflows/test_coarse.yml'

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        # Due to https://github.com/actions/runner/issues/849, we have to use quotes for '3.0'
        ruby: ['3.4', '4.0']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      - name: Set up Ruby
        uses: ruby/setup-ruby@14594264cd68ce8a2345dd349bc3d138a4ef85c8  # v1.327.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "<>"
      - name: Run coarse tests and collect coverage
        run: |
          ruby --version
          time bundle exec rspec --format documentation spec/lib/coarse/*
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f  # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage
