name: Minimal macOS tests

on:
  push:
    branches: [ master, devel ]
    paths:
      - '!*.md'
      - '*.gemspec'
      - '**.rb'
      - 'Rakefile'
      - 'Gemfile'
      - 'Gemfile.lock'
      - 'bin/tetra'
      - 'spec/**'
      - 'lib/template/bundled/'
      - '.github/workflows/test_min_macos.yml'
  pull_request:
    branches: [ master, devel ]
    paths:
      - '!*.md'
      - '*.gemspec'
      - '**.rb'
      - 'Rakefile'
      - 'Gemfile'
      - 'Gemfile.lock'
      - 'bin/tetra'
      - 'spec/**'
      - 'lib/template/bundled/'
      - '.github/workflows/test_min_macos.yml'

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        # Due to https://github.com/actions/runner/issues/849, we have to use quotes for '3.0'
        ruby: ['4.0']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      - name: Set up Ruby
        uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b  # v1.321.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "<>"
      - name: Run fine tests and collect coverage
        run: |
          ruby --version
          time bundle exec rspec --format documentation spec/lib/fine/version_matcher_spec.rb
          time bundle exec rspec --format documentation spec/lib/fine/pom_spec.rb
          time bundle exec rspec --format documentation spec/lib/fine/unzip_spec.rb
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@303a32d7a59b442fa8d48b6a1cc6825c09c847a5  # v7.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage
